// AutoGenerate.py Version 1.1
// The following content is auto generated by AutoGenerate.py
// Written by Zijian Zhao
// github.com/JackZhao98
// Date created: 2020/03/01  22:02:57


//	Selector Summary
//	4'b0011	: three
//	4'b0110	: six
//	4'b0010	: two
//	4'b0100	: four
//	4'b0000	: zero
//	4'b1000	: eight
//	4'b0101	: five
//	4'b0001	: one
//	4'b0111	: seven
//	4'b1001	: nine


module drawNumber#(parameter ratio = 1)
	(
	    input  wire        rst,
	    input  wire [31:0] ox,
	    input  wire [31:0] oy,
	    input  wire [31:0] X,
	    input  wire [31:0] Y,
	    input  wire [3:0]  select,	// Select Pattern
	    output reg  [11:0] objectWidth,
	    output reg  [11:0] objectHeight,
	    output reg 	       inHitBox,
	    output reg 	       inWhite,
	    output reg 	       inGrey);
		
localparam px = ratio;


// Auto Generated: Number/three
localparam threeWidth = 20 * px;
localparam threeHeight = 21 * px;
wire inHitBox_three;
wire inGrey_three;
wire inBlank_three;
wire inWhite_three;

assign inHitBox_three = (X > ox) && (X <= threeWidth) && (Y > oy) && (Y <= threeHeight);

assign inBlank_three = 
	   ((X > ox) && (X <= ox + 1 * px) && (Y == oy))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 1 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 2 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 3 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 4 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 5 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 6 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 7 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 8 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 9 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 10 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 11 * px))
	|| ((X > ox) && (X <= ox + 11 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 12 * px))
	|| ((X > ox) && (X <= ox + 11 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 13 * px))
	|| ((X > ox) && (X <= ox + 11 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 17 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 18 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 19 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 20 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 20 * px));
	// Total 84 lines.

assign inGrey_three = 
	   ((X > ox + 2 * px) && (X <= ox + 17 * px) && (Y == oy))
	|| ((X > ox + 2 * px) && (X <= ox + 17 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 17 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 14 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 14 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 14 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 14 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 15 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 16 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy + 20 * px));
	// Total 48 lines.

assign inWhite_three = inHitBox_three & ~inBlank_three & ~inGrey_three;

// End of Auto Generate: Number/three

// Auto Generated: Number/six
localparam sixWidth = 20 * px;
localparam sixHeight = 21 * px;
wire inHitBox_six;
wire inGrey_six;
wire inBlank_six;
wire inWhite_six;

assign inHitBox_six = (X > ox) && (X <= sixWidth) && (Y > oy) && (Y <= sixHeight);

assign inBlank_six = 
	   ((X > ox) && (X <= ox + 4 * px) && (Y == oy))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 1 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 2 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 8 * px) && (X <= ox + 19 * px) && (Y == oy + 3 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 8 * px) && (X <= ox + 19 * px) && (Y == oy + 4 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 8 * px) && (X <= ox + 19 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 19 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 19 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 19 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 17 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 18 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 19 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 20 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 20 * px));
	// Total 72 lines.

assign inGrey_six = 
	   ((X > ox + 5 * px) && (X <= ox + 14 * px) && (Y == oy))
	|| ((X > ox + 5 * px) && (X <= ox + 14 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 14 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 7 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 7 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 7 * px) && (Y == oy + 5 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 6 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 7 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 8 * px))
	|| ((X > ox) && (X <= ox + 14 * px) && (Y == oy + 9 * px))
	|| ((X > ox) && (X <= ox + 14 * px) && (Y == oy + 10 * px))
	|| ((X > ox) && (X <= ox + 14 * px) && (Y == oy + 11 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 12 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 13 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 14 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 15 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 16 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy + 20 * px));
	// Total 54 lines.

assign inWhite_six = inHitBox_six & ~inBlank_six & ~inGrey_six;

// End of Auto Generate: Number/six

// Auto Generated: Number/two
localparam twoWidth = 20 * px;
localparam twoHeight = 21 * px;
wire inHitBox_two;
wire inGrey_two;
wire inBlank_two;
wire inWhite_two;

assign inHitBox_two = (X > ox) && (X <= twoWidth) && (Y > oy) && (Y <= twoHeight);

assign inBlank_two = 
	   ((X > ox) && (X <= ox + 1 * px) && (Y == oy))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 1 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 5 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 6 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 7 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 8 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 9 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 10 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 11 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 12 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 13 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 8 * px) && (X <= ox + 19 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 8 * px) && (X <= ox + 19 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 8 * px) && (X <= ox + 19 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 20 * px));
	// Total 72 lines.

assign inGrey_two = 
	   ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy))
	|| ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy + 2 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 3 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 4 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 17 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 17 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 17 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 14 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 14 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 14 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 12 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 12 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 12 * px) && (Y == oy + 14 * px))
	|| ((X > ox) && (X <= ox + 7 * px) && (Y == oy + 15 * px))
	|| ((X > ox) && (X <= ox + 7 * px) && (Y == oy + 16 * px))
	|| ((X > ox) && (X <= ox + 7 * px) && (Y == oy + 17 * px))
	|| ((X > ox) && (X <= ox + 17 * px) && (Y == oy + 18 * px))
	|| ((X > ox) && (X <= ox + 17 * px) && (Y == oy + 19 * px))
	|| ((X > ox) && (X <= ox + 17 * px) && (Y == oy + 20 * px));
	// Total 48 lines.

assign inWhite_two = inHitBox_two & ~inBlank_two & ~inGrey_two;

// End of Auto Generate: Number/two

// Auto Generated: Number/four
localparam fourWidth = 20 * px;
localparam fourHeight = 21 * px;
wire inHitBox_four;
wire inGrey_four;
wire inBlank_four;
wire inWhite_four;

assign inHitBox_four = (X > ox) && (X <= fourWidth) && (Y > oy) && (Y <= fourHeight);

assign inBlank_four = 
	   ((X > ox) && (X <= ox + 6 * px) && (Y == oy))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 1 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 2 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 3 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 4 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 5 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 8 * px) && (X <= ox + 9 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 6 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 8 * px) && (X <= ox + 9 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 7 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 8 * px) && (X <= ox + 9 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 9 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 9 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 9 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 14 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 15 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 16 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 17 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 18 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 19 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 20 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 20 * px));
	// Total 84 lines.

assign inGrey_four = 
	   ((X > ox + 7 * px) && (X <= ox + 14 * px) && (Y == oy))
	|| ((X > ox + 7 * px) && (X <= ox + 14 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 14 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 14 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 14 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 14 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 7 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 7 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 7 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 8 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 9 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 10 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 11 * px))
	|| ((X > ox) && (X <= ox + 17 * px) && (Y == oy + 12 * px))
	|| ((X > ox) && (X <= ox + 17 * px) && (Y == oy + 13 * px))
	|| ((X > ox) && (X <= ox + 17 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 20 * px));
	// Total 54 lines.

assign inWhite_four = inHitBox_four & ~inBlank_four & ~inGrey_four;

// End of Auto Generate: Number/four

// Auto Generated: Number/zero
localparam zeroWidth = 20 * px;
localparam zeroHeight = 21 * px;
wire inHitBox_zero;
wire inGrey_zero;
wire inBlank_zero;
wire inWhite_zero;

assign inHitBox_zero = (X > ox) && (X <= zeroWidth) && (Y > oy) && (Y <= zeroHeight);

assign inBlank_zero = 
	   ((X > ox) && (X <= ox + 4 * px) && (Y == oy))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 1 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 2 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 9 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 3 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 9 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 4 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 9 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 14 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 8 * px) && (X <= ox + 11 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 15 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 8 * px) && (X <= ox + 11 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 16 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 8 * px) && (X <= ox + 11 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 17 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 18 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 19 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 20 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 20 * px));
	// Total 96 lines.

assign inGrey_zero = 
	   ((X > ox + 5 * px) && (X <= ox + 12 * px) && (Y == oy))
	|| ((X > ox + 5 * px) && (X <= ox + 12 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 12 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 4 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 4 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 4 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 5 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 6 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 7 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 8 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 9 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 10 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 11 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 12 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 13 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 7 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 14 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 7 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 14 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 7 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 14 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 12 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 12 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 12 * px) && (Y == oy + 20 * px));
	// Total 72 lines.

assign inWhite_zero = inHitBox_zero & ~inBlank_zero & ~inGrey_zero;

// End of Auto Generate: Number/zero

// Auto Generated: Number/eight
localparam eightWidth = 20 * px;
localparam eightHeight = 21 * px;
wire inHitBox_eight;
wire inGrey_eight;
wire inBlank_eight;
wire inWhite_eight;

assign inHitBox_eight = (X > ox) && (X <= eightWidth) && (Y > oy) && (Y <= eightHeight);

assign inBlank_eight = 
	   ((X > ox) && (X <= ox + 1 * px) && (Y == oy))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 1 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 8 * px) && (X <= ox + 11 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 8 * px) && (X <= ox + 11 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 8 * px) && (X <= ox + 11 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 8 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 9 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 10 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 3 * px) && (X <= ox + 6 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 3 * px) && (X <= ox + 6 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 3 * px) && (X <= ox + 6 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 3 * px) && (X <= ox + 11 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 3 * px) && (X <= ox + 11 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 3 * px) && (X <= ox + 11 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 17 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 18 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 19 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 20 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 20 * px));
	// Total 84 lines.

assign inGrey_eight = 
	   ((X > ox + 2 * px) && (X <= ox + 12 * px) && (Y == oy))
	|| ((X > ox + 2 * px) && (X <= ox + 12 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 12 * px) && (Y == oy + 2 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 14 * px) && (Y == oy + 3 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 14 * px) && (Y == oy + 4 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 14 * px) && (Y == oy + 5 * px))
	|| ((X > ox) && (X <= ox + 7 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 14 * px) && (Y == oy + 6 * px))
	|| ((X > ox) && (X <= ox + 7 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 14 * px) && (Y == oy + 7 * px))
	|| ((X > ox) && (X <= ox + 7 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 14 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 12 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 12 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 12 * px) && (Y == oy + 11 * px))
	|| ((X > ox) && (X <= ox + 2 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 17 * px) && (Y == oy + 12 * px))
	|| ((X > ox) && (X <= ox + 2 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 17 * px) && (Y == oy + 13 * px))
	|| ((X > ox) && (X <= ox + 2 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 17 * px) && (Y == oy + 14 * px))
	|| ((X > ox) && (X <= ox + 2 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 15 * px))
	|| ((X > ox) && (X <= ox + 2 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 16 * px))
	|| ((X > ox) && (X <= ox + 2 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy + 20 * px));
	// Total 66 lines.

assign inWhite_eight = inHitBox_eight & ~inBlank_eight & ~inGrey_eight;

// End of Auto Generate: Number/eight

// Auto Generated: Number/five
localparam fiveWidth = 20 * px;
localparam fiveHeight = 21 * px;
wire inHitBox_five;
wire inGrey_five;
wire inBlank_five;
wire inWhite_five;

assign inHitBox_five = (X > ox) && (X <= fiveWidth) && (Y > oy) && (Y <= fiveHeight);

assign inBlank_five = 
	   ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 19 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 19 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 19 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 8 * px))
	|| ((X > ox) && (X <= ox + 11 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 9 * px))
	|| ((X > ox) && (X <= ox + 11 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 10 * px))
	|| ((X > ox) && (X <= ox + 11 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 11 * px))
	|| ((X > ox) && (X <= ox + 11 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 12 * px))
	|| ((X > ox) && (X <= ox + 11 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 13 * px))
	|| ((X > ox) && (X <= ox + 11 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 17 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 18 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 19 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 20 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 20 * px));
	// Total 66 lines.

assign inGrey_five = 
	   ((X > ox) && (X <= ox + 14 * px) && (Y == oy))
	|| ((X > ox) && (X <= ox + 14 * px) && (Y == oy + 1 * px))
	|| ((X > ox) && (X <= ox + 14 * px) && (Y == oy + 2 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 3 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 4 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 5 * px))
	|| ((X > ox) && (X <= ox + 14 * px) && (Y == oy + 6 * px))
	|| ((X > ox) && (X <= ox + 14 * px) && (Y == oy + 7 * px))
	|| ((X > ox) && (X <= ox + 14 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 14 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 15 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 16 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy + 20 * px));
	// Total 48 lines.

assign inWhite_five = inHitBox_five & ~inBlank_five & ~inGrey_five;

// End of Auto Generate: Number/five

// Auto Generated: Number/one
localparam oneWidth = 20 * px;
localparam oneHeight = 21 * px;
wire inHitBox_one;
wire inGrey_one;
wire inBlank_one;
wire inWhite_one;

assign inHitBox_one = (X > ox) && (X <= oneWidth) && (Y > oy) && (Y <= oneHeight);

assign inBlank_one = 
	   ((X > ox) && (X <= ox + 6 * px) && (Y == oy))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 1 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 2 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 3 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 4 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 5 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 6 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 7 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 8 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 9 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 10 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 11 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 12 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 13 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 14 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 15 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 16 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 17 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 18 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 19 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 20 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 20 * px));
	// Total 84 lines.

assign inGrey_one = 
	   ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 12 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 12 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 12 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 17 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 17 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 17 * px) && (Y == oy + 20 * px));
	// Total 42 lines.

assign inWhite_one = inHitBox_one & ~inBlank_one & ~inGrey_one;

// End of Auto Generate: Number/one

// Auto Generated: Number/seven
localparam sevenWidth = 20 * px;
localparam sevenHeight = 21 * px;
wire inHitBox_seven;
wire inGrey_seven;
wire inBlank_seven;
wire inWhite_seven;

assign inHitBox_seven = (X > ox) && (X <= sevenWidth) && (Y > oy) && (Y <= sevenHeight);

assign inBlank_seven = 
	   ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 5 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 6 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 7 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 19 * px) && (Y == oy + 8 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 9 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 10 * px))
	|| ((X > ox) && (X <= ox + 6 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 19 * px) && (Y == oy + 11 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 19 * px) && (Y == oy + 12 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 19 * px) && (Y == oy + 13 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 19 * px) && (Y == oy + 14 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 19 * px) && (Y == oy + 15 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 19 * px) && (Y == oy + 16 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 19 * px) && (Y == oy + 17 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 19 * px) && (Y == oy + 18 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 19 * px) && (Y == oy + 19 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 20 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 19 * px) && (Y == oy + 20 * px));
	// Total 78 lines.

assign inGrey_seven = 
	   ((X > ox) && (X <= ox + 17 * px) && (Y == oy))
	|| ((X > ox) && (X <= ox + 17 * px) && (Y == oy + 1 * px))
	|| ((X > ox) && (X <= ox + 17 * px) && (Y == oy + 2 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 3 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 4 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 7 * px) && (X <= ox + 12 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 9 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 9 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 9 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 9 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 9 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 9 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 9 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 9 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 9 * px) && (Y == oy + 20 * px));
	// Total 48 lines.

assign inWhite_seven = inHitBox_seven & ~inBlank_seven & ~inGrey_seven;

// End of Auto Generate: Number/seven

// Auto Generated: Number/nine
localparam nineWidth = 18 * px;
localparam nineHeight = 21 * px;
wire inHitBox_nine;
wire inGrey_nine;
wire inBlank_nine;
wire inWhite_nine;

assign inHitBox_nine = (X > ox) && (X <= nineWidth) && (Y > oy) && (Y <= nineHeight);

assign inBlank_nine = 
	   ((X > ox) && (X <= ox + 1 * px) && (Y == oy))
	|| ((X > ox + 15 * px) && (X <= ox + 17 * px) && (Y == oy))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 17 * px) && (Y == oy + 1 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 17 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 5 * px) && (X <= ox + 11 * px) && (Y == oy + 8 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 9 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 10 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 11 * px))
	|| ((X > ox) && (X <= ox + 11 * px) && (Y == oy + 12 * px))
	|| ((X > ox) && (X <= ox + 11 * px) && (Y == oy + 13 * px))
	|| ((X > ox) && (X <= ox + 11 * px) && (Y == oy + 14 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 17 * px) && (Y == oy + 15 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 17 * px) && (Y == oy + 16 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 15 * px) && (X <= ox + 17 * px) && (Y == oy + 17 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 17 * px) && (Y == oy + 18 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 17 * px) && (Y == oy + 19 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 20 * px))
	|| ((X > ox + 13 * px) && (X <= ox + 17 * px) && (Y == oy + 20 * px));
	// Total 60 lines.

assign inGrey_nine = 
	   ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy))
	|| ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 14 * px) && (Y == oy + 2 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 3 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 4 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 5 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 6 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 7 * px))
	|| ((X > ox) && (X <= ox + 4 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 17 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 17 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 17 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 14 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 12 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 12 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 12 * px) && (Y == oy + 20 * px));
	// Total 54 lines.

assign inWhite_nine = inHitBox_nine & ~inBlank_nine & ~inGrey_nine;

// End of Auto Generate: Number/nine


always @(*) begin

case(select)

4'b0011: begin	// Case: three
	inHitBox <= inHitBox_three;
	inWhite <= inWhite_three;
	inGrey <= inGrey_three;
	objectWidth <= threeWidth;
	objectHeight <= threeHeight;
end // end of case

4'b0110: begin	// Case: six
	inHitBox <= inHitBox_six;
	inWhite <= inWhite_six;
	inGrey <= inGrey_six;
	objectWidth <= sixWidth;
	objectHeight <= sixHeight;
end // end of case

4'b0010: begin	// Case: two
	inHitBox <= inHitBox_two;
	inWhite <= inWhite_two;
	inGrey <= inGrey_two;
	objectWidth <= twoWidth;
	objectHeight <= twoHeight;
end // end of case

4'b0100: begin	// Case: four
	inHitBox <= inHitBox_four;
	inWhite <= inWhite_four;
	inGrey <= inGrey_four;
	objectWidth <= fourWidth;
	objectHeight <= fourHeight;
end // end of case

4'b0000: begin	// Case: zero
	inHitBox <= inHitBox_zero;
	inWhite <= inWhite_zero;
	inGrey <= inGrey_zero;
	objectWidth <= zeroWidth;
	objectHeight <= zeroHeight;
end // end of case

4'b1000: begin	// Case: eight
	inHitBox <= inHitBox_eight;
	inWhite <= inWhite_eight;
	inGrey <= inGrey_eight;
	objectWidth <= eightWidth;
	objectHeight <= eightHeight;
end // end of case

4'b0101: begin	// Case: five
	inHitBox <= inHitBox_five;
	inWhite <= inWhite_five;
	inGrey <= inGrey_five;
	objectWidth <= fiveWidth;
	objectHeight <= fiveHeight;
end // end of case

4'b0001: begin	// Case: one
	inHitBox <= inHitBox_one;
	inWhite <= inWhite_one;
	inGrey <= inGrey_one;
	objectWidth <= oneWidth;
	objectHeight <= oneHeight;
end // end of case

4'b0111: begin	// Case: seven
	inHitBox <= inHitBox_seven;
	inWhite <= inWhite_seven;
	inGrey <= inGrey_seven;
	objectWidth <= sevenWidth;
	objectHeight <= sevenHeight;
end // end of case

4'b1001: begin	// Case: nine
	inHitBox <= inHitBox_nine;
	inWhite <= inWhite_nine;
	inGrey <= inGrey_nine;
	objectWidth <= nineWidth;
	objectHeight <= nineHeight;
end // end of case


endcase

end	// end of always @(*)

endmodule // end of Number

// Auto generate complete.
// Direct modification of this file may cause unexpected issues.
// Copyright © 2020 Zijian Zhao. All rights reserved.
		
