
// The following content is generated by ./AutoGenerate.py
// Written by Zijian Zhao
// github.com/JackZhao98

module drawNumber#(parameter ratio = 1),
(
	    input wire animateClk,
	    input wire rst,
	    input wire [9:0] ox,
	    input wire [8:0] oy,
	    input wire [9:0] X,
	    input wire [8:0] Y,
	    input wire [2:0] select,	// Select Pattern
	    output wire [11:0] objectWidth,
	    output wire [6:0] objectHeight,
	    output wire inHitBox,
	    output wire inWhite,
	    output wire inGrey);

		
localparam px = ratio
// Auto Generated: Number/three
localparam threeWidth = 20 * px;
localparam threeHeight = 21 * px;
wire inHitBox_three;
wire inGrey_three;
wire inBlank_three;
wire inWhite_three;

assign inHitBox_three = (X > ox) && (X <= threeWidth) && (Y > oy) && (Y <= threeHeight);

assign inGrey_three = 
     (X > ox + 2 * px) && (X <= ox + 17 * px) && (Y > oy) && (Y <= oy) ||
     (X > ox + 2 * px) && (X <= ox + 17 * px) && (Y > oy + 1 * px) && (Y <= oy + 1 * px) ||
     (X > ox + 2 * px) && (X <= ox + 17 * px) && (Y > oy + 2 * px) && (Y <= oy + 2 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 3 * px) && (Y <= oy + 3 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 4 * px) && (Y <= oy + 4 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 5 * px) && (Y <= oy + 5 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 6 * px) && (Y <= oy + 6 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 7 * px) && (Y <= oy + 7 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 8 * px) && (Y <= oy + 8 * px) ||
     (X > ox + 5 * px) && (X <= ox + 14 * px) && (Y > oy + 9 * px) && (Y <= oy + 9 * px) ||
     (X > ox + 5 * px) && (X <= ox + 14 * px) && (Y > oy + 10 * px) && (Y <= oy + 10 * px) ||
     (X > ox + 5 * px) && (X <= ox + 14 * px) && (Y > oy + 11 * px) && (Y <= oy + 11 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 12 * px) && (Y <= oy + 12 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 13 * px) && (Y <= oy + 13 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 14 * px) && (Y <= oy + 14 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 15 * px) && (Y <= oy + 15 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 15 * px) && (Y <= oy + 15 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 16 * px) && (Y <= oy + 16 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 16 * px) && (Y <= oy + 16 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 17 * px) && (Y <= oy + 17 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 17 * px) && (Y <= oy + 17 * px) ||
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy + 18 * px) && (Y <= oy + 18 * px) ||
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy + 19 * px) && (Y <= oy + 19 * px) ||
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy + 20 * px) && (Y <= oy + 20 * px);
	// Total 48 lines.

assign inWhite_three = inHitBox_three & ~inBlank_three & ~inGrey_three;

// End of Auto Generate: Number/three

// Auto Generated: Number/six
localparam sixWidth = 20 * px;
localparam sixHeight = 21 * px;
wire inHitBox_six;
wire inGrey_six;
wire inBlank_six;
wire inWhite_six;

assign inHitBox_six = (X > ox) && (X <= sixWidth) && (Y > oy) && (Y <= sixHeight);

assign inGrey_six = 
     (X > ox + 5 * px) && (X <= ox + 14 * px) && (Y > oy) && (Y <= oy) ||
     (X > ox + 5 * px) && (X <= ox + 14 * px) && (Y > oy + 1 * px) && (Y <= oy + 1 * px) ||
     (X > ox + 5 * px) && (X <= ox + 14 * px) && (Y > oy + 2 * px) && (Y <= oy + 2 * px) ||
     (X > ox + 2 * px) && (X <= ox + 7 * px) && (Y > oy + 3 * px) && (Y <= oy + 3 * px) ||
     (X > ox + 2 * px) && (X <= ox + 7 * px) && (Y > oy + 4 * px) && (Y <= oy + 4 * px) ||
     (X > ox + 2 * px) && (X <= ox + 7 * px) && (Y > oy + 5 * px) && (Y <= oy + 5 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 6 * px) && (Y <= oy + 6 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 7 * px) && (Y <= oy + 7 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 8 * px) && (Y <= oy + 8 * px) ||
     (X > ox) && (X <= ox + 14 * px) && (Y > oy + 9 * px) && (Y <= oy + 9 * px) ||
     (X > ox) && (X <= ox + 14 * px) && (Y > oy + 10 * px) && (Y <= oy + 10 * px) ||
     (X > ox) && (X <= ox + 14 * px) && (Y > oy + 11 * px) && (Y <= oy + 11 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 12 * px) && (Y <= oy + 12 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 12 * px) && (Y <= oy + 12 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 13 * px) && (Y <= oy + 13 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 13 * px) && (Y <= oy + 13 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 14 * px) && (Y <= oy + 14 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 14 * px) && (Y <= oy + 14 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 15 * px) && (Y <= oy + 15 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 15 * px) && (Y <= oy + 15 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 16 * px) && (Y <= oy + 16 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 16 * px) && (Y <= oy + 16 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 17 * px) && (Y <= oy + 17 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 17 * px) && (Y <= oy + 17 * px) ||
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy + 18 * px) && (Y <= oy + 18 * px) ||
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy + 19 * px) && (Y <= oy + 19 * px) ||
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy + 20 * px) && (Y <= oy + 20 * px);
	// Total 54 lines.

assign inWhite_six = inHitBox_six & ~inBlank_six & ~inGrey_six;

// End of Auto Generate: Number/six

// Auto Generated: Number/two
localparam twoWidth = 20 * px;
localparam twoHeight = 21 * px;
wire inHitBox_two;
wire inGrey_two;
wire inBlank_two;
wire inWhite_two;

assign inHitBox_two = (X > ox) && (X <= twoWidth) && (Y > oy) && (Y <= twoHeight);

assign inGrey_two = 
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy) && (Y <= oy) ||
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy + 1 * px) && (Y <= oy + 1 * px) ||
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy + 2 * px) && (Y <= oy + 2 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 3 * px) && (Y <= oy + 3 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 3 * px) && (Y <= oy + 3 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 4 * px) && (Y <= oy + 4 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 4 * px) && (Y <= oy + 4 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 5 * px) && (Y <= oy + 5 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 5 * px) && (Y <= oy + 5 * px) ||
     (X > ox + 10 * px) && (X <= ox + 17 * px) && (Y > oy + 6 * px) && (Y <= oy + 6 * px) ||
     (X > ox + 10 * px) && (X <= ox + 17 * px) && (Y > oy + 7 * px) && (Y <= oy + 7 * px) ||
     (X > ox + 10 * px) && (X <= ox + 17 * px) && (Y > oy + 8 * px) && (Y <= oy + 8 * px) ||
     (X > ox + 5 * px) && (X <= ox + 14 * px) && (Y > oy + 9 * px) && (Y <= oy + 9 * px) ||
     (X > ox + 5 * px) && (X <= ox + 14 * px) && (Y > oy + 10 * px) && (Y <= oy + 10 * px) ||
     (X > ox + 5 * px) && (X <= ox + 14 * px) && (Y > oy + 11 * px) && (Y <= oy + 11 * px) ||
     (X > ox + 2 * px) && (X <= ox + 12 * px) && (Y > oy + 12 * px) && (Y <= oy + 12 * px) ||
     (X > ox + 2 * px) && (X <= ox + 12 * px) && (Y > oy + 13 * px) && (Y <= oy + 13 * px) ||
     (X > ox + 2 * px) && (X <= ox + 12 * px) && (Y > oy + 14 * px) && (Y <= oy + 14 * px) ||
     (X > ox) && (X <= ox + 7 * px) && (Y > oy + 15 * px) && (Y <= oy + 15 * px) ||
     (X > ox) && (X <= ox + 7 * px) && (Y > oy + 16 * px) && (Y <= oy + 16 * px) ||
     (X > ox) && (X <= ox + 7 * px) && (Y > oy + 17 * px) && (Y <= oy + 17 * px) ||
     (X > ox) && (X <= ox + 17 * px) && (Y > oy + 18 * px) && (Y <= oy + 18 * px) ||
     (X > ox) && (X <= ox + 17 * px) && (Y > oy + 19 * px) && (Y <= oy + 19 * px) ||
     (X > ox) && (X <= ox + 17 * px) && (Y > oy + 20 * px) && (Y <= oy + 20 * px);
	// Total 48 lines.

assign inWhite_two = inHitBox_two & ~inBlank_two & ~inGrey_two;

// End of Auto Generate: Number/two

// Auto Generated: Number/four
localparam fourWidth = 20 * px;
localparam fourHeight = 21 * px;
wire inHitBox_four;
wire inGrey_four;
wire inBlank_four;
wire inWhite_four;

assign inHitBox_four = (X > ox) && (X <= fourWidth) && (Y > oy) && (Y <= fourHeight);

assign inGrey_four = 
     (X > ox + 7 * px) && (X <= ox + 14 * px) && (Y > oy) && (Y <= oy) ||
     (X > ox + 7 * px) && (X <= ox + 14 * px) && (Y > oy + 1 * px) && (Y <= oy + 1 * px) ||
     (X > ox + 7 * px) && (X <= ox + 14 * px) && (Y > oy + 2 * px) && (Y <= oy + 2 * px) ||
     (X > ox + 5 * px) && (X <= ox + 14 * px) && (Y > oy + 3 * px) && (Y <= oy + 3 * px) ||
     (X > ox + 5 * px) && (X <= ox + 14 * px) && (Y > oy + 4 * px) && (Y <= oy + 4 * px) ||
     (X > ox + 5 * px) && (X <= ox + 14 * px) && (Y > oy + 5 * px) && (Y <= oy + 5 * px) ||
     (X > ox + 2 * px) && (X <= ox + 7 * px) && (Y > oy + 6 * px) && (Y <= oy + 6 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 6 * px) && (Y <= oy + 6 * px) ||
     (X > ox + 2 * px) && (X <= ox + 7 * px) && (Y > oy + 7 * px) && (Y <= oy + 7 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 7 * px) && (Y <= oy + 7 * px) ||
     (X > ox + 2 * px) && (X <= ox + 7 * px) && (Y > oy + 8 * px) && (Y <= oy + 8 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 8 * px) && (Y <= oy + 8 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 9 * px) && (Y <= oy + 9 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 9 * px) && (Y <= oy + 9 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 10 * px) && (Y <= oy + 10 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 10 * px) && (Y <= oy + 10 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 11 * px) && (Y <= oy + 11 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 11 * px) && (Y <= oy + 11 * px) ||
     (X > ox) && (X <= ox + 17 * px) && (Y > oy + 12 * px) && (Y <= oy + 12 * px) ||
     (X > ox) && (X <= ox + 17 * px) && (Y > oy + 13 * px) && (Y <= oy + 13 * px) ||
     (X > ox) && (X <= ox + 17 * px) && (Y > oy + 14 * px) && (Y <= oy + 14 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 15 * px) && (Y <= oy + 15 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 16 * px) && (Y <= oy + 16 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 17 * px) && (Y <= oy + 17 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 18 * px) && (Y <= oy + 18 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 19 * px) && (Y <= oy + 19 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 20 * px) && (Y <= oy + 20 * px);
	// Total 54 lines.

assign inWhite_four = inHitBox_four & ~inBlank_four & ~inGrey_four;

// End of Auto Generate: Number/four

// Auto Generated: Number/zero
localparam zeroWidth = 20 * px;
localparam zeroHeight = 21 * px;
wire inHitBox_zero;
wire inGrey_zero;
wire inBlank_zero;
wire inWhite_zero;

assign inHitBox_zero = (X > ox) && (X <= zeroWidth) && (Y > oy) && (Y <= zeroHeight);

assign inGrey_zero = 
     (X > ox + 5 * px) && (X <= ox + 12 * px) && (Y > oy) && (Y <= oy) ||
     (X > ox + 5 * px) && (X <= ox + 12 * px) && (Y > oy + 1 * px) && (Y <= oy + 1 * px) ||
     (X > ox + 5 * px) && (X <= ox + 12 * px) && (Y > oy + 2 * px) && (Y <= oy + 2 * px) ||
     (X > ox + 2 * px) && (X <= ox + 4 * px) && (Y > oy + 3 * px) && (Y <= oy + 3 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 3 * px) && (Y <= oy + 3 * px) ||
     (X > ox + 2 * px) && (X <= ox + 4 * px) && (Y > oy + 4 * px) && (Y <= oy + 4 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 4 * px) && (Y <= oy + 4 * px) ||
     (X > ox + 2 * px) && (X <= ox + 4 * px) && (Y > oy + 5 * px) && (Y <= oy + 5 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 5 * px) && (Y <= oy + 5 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 6 * px) && (Y <= oy + 6 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 6 * px) && (Y <= oy + 6 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 7 * px) && (Y <= oy + 7 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 7 * px) && (Y <= oy + 7 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 8 * px) && (Y <= oy + 8 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 8 * px) && (Y <= oy + 8 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 9 * px) && (Y <= oy + 9 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 9 * px) && (Y <= oy + 9 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 10 * px) && (Y <= oy + 10 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 10 * px) && (Y <= oy + 10 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 11 * px) && (Y <= oy + 11 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 11 * px) && (Y <= oy + 11 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 12 * px) && (Y <= oy + 12 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 12 * px) && (Y <= oy + 12 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 13 * px) && (Y <= oy + 13 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 13 * px) && (Y <= oy + 13 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 14 * px) && (Y <= oy + 14 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 14 * px) && (Y <= oy + 14 * px) ||
     (X > ox + 2 * px) && (X <= ox + 7 * px) && (Y > oy + 15 * px) && (Y <= oy + 15 * px) ||
     (X > ox + 12 * px) && (X <= ox + 14 * px) && (Y > oy + 15 * px) && (Y <= oy + 15 * px) ||
     (X > ox + 2 * px) && (X <= ox + 7 * px) && (Y > oy + 16 * px) && (Y <= oy + 16 * px) ||
     (X > ox + 12 * px) && (X <= ox + 14 * px) && (Y > oy + 16 * px) && (Y <= oy + 16 * px) ||
     (X > ox + 2 * px) && (X <= ox + 7 * px) && (Y > oy + 17 * px) && (Y <= oy + 17 * px) ||
     (X > ox + 12 * px) && (X <= ox + 14 * px) && (Y > oy + 17 * px) && (Y <= oy + 17 * px) ||
     (X > ox + 5 * px) && (X <= ox + 12 * px) && (Y > oy + 18 * px) && (Y <= oy + 18 * px) ||
     (X > ox + 5 * px) && (X <= ox + 12 * px) && (Y > oy + 19 * px) && (Y <= oy + 19 * px) ||
     (X > ox + 5 * px) && (X <= ox + 12 * px) && (Y > oy + 20 * px) && (Y <= oy + 20 * px);
	// Total 72 lines.

assign inWhite_zero = inHitBox_zero & ~inBlank_zero & ~inGrey_zero;

// End of Auto Generate: Number/zero

// Auto Generated: Number/eight
localparam eightWidth = 20 * px;
localparam eightHeight = 21 * px;
wire inHitBox_eight;
wire inGrey_eight;
wire inBlank_eight;
wire inWhite_eight;

assign inHitBox_eight = (X > ox) && (X <= eightWidth) && (Y > oy) && (Y <= eightHeight);

assign inGrey_eight = 
     (X > ox + 2 * px) && (X <= ox + 12 * px) && (Y > oy) && (Y <= oy) ||
     (X > ox + 2 * px) && (X <= ox + 12 * px) && (Y > oy + 1 * px) && (Y <= oy + 1 * px) ||
     (X > ox + 2 * px) && (X <= ox + 12 * px) && (Y > oy + 2 * px) && (Y <= oy + 2 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 3 * px) && (Y <= oy + 3 * px) ||
     (X > ox + 12 * px) && (X <= ox + 14 * px) && (Y > oy + 3 * px) && (Y <= oy + 3 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 4 * px) && (Y <= oy + 4 * px) ||
     (X > ox + 12 * px) && (X <= ox + 14 * px) && (Y > oy + 4 * px) && (Y <= oy + 4 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 5 * px) && (Y <= oy + 5 * px) ||
     (X > ox + 12 * px) && (X <= ox + 14 * px) && (Y > oy + 5 * px) && (Y <= oy + 5 * px) ||
     (X > ox) && (X <= ox + 7 * px) && (Y > oy + 6 * px) && (Y <= oy + 6 * px) ||
     (X > ox + 12 * px) && (X <= ox + 14 * px) && (Y > oy + 6 * px) && (Y <= oy + 6 * px) ||
     (X > ox) && (X <= ox + 7 * px) && (Y > oy + 7 * px) && (Y <= oy + 7 * px) ||
     (X > ox + 12 * px) && (X <= ox + 14 * px) && (Y > oy + 7 * px) && (Y <= oy + 7 * px) ||
     (X > ox) && (X <= ox + 7 * px) && (Y > oy + 8 * px) && (Y <= oy + 8 * px) ||
     (X > ox + 12 * px) && (X <= ox + 14 * px) && (Y > oy + 8 * px) && (Y <= oy + 8 * px) ||
     (X > ox + 2 * px) && (X <= ox + 12 * px) && (Y > oy + 9 * px) && (Y <= oy + 9 * px) ||
     (X > ox + 2 * px) && (X <= ox + 12 * px) && (Y > oy + 10 * px) && (Y <= oy + 10 * px) ||
     (X > ox + 2 * px) && (X <= ox + 12 * px) && (Y > oy + 11 * px) && (Y <= oy + 11 * px) ||
     (X > ox) && (X <= ox + 2 * px) && (Y > oy + 12 * px) && (Y <= oy + 12 * px) ||
     (X > ox + 7 * px) && (X <= ox + 17 * px) && (Y > oy + 12 * px) && (Y <= oy + 12 * px) ||
     (X > ox) && (X <= ox + 2 * px) && (Y > oy + 13 * px) && (Y <= oy + 13 * px) ||
     (X > ox + 7 * px) && (X <= ox + 17 * px) && (Y > oy + 13 * px) && (Y <= oy + 13 * px) ||
     (X > ox) && (X <= ox + 2 * px) && (Y > oy + 14 * px) && (Y <= oy + 14 * px) ||
     (X > ox + 7 * px) && (X <= ox + 17 * px) && (Y > oy + 14 * px) && (Y <= oy + 14 * px) ||
     (X > ox) && (X <= ox + 2 * px) && (Y > oy + 15 * px) && (Y <= oy + 15 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 15 * px) && (Y <= oy + 15 * px) ||
     (X > ox) && (X <= ox + 2 * px) && (Y > oy + 16 * px) && (Y <= oy + 16 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 16 * px) && (Y <= oy + 16 * px) ||
     (X > ox) && (X <= ox + 2 * px) && (Y > oy + 17 * px) && (Y <= oy + 17 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 17 * px) && (Y <= oy + 17 * px) ||
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy + 18 * px) && (Y <= oy + 18 * px) ||
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy + 19 * px) && (Y <= oy + 19 * px) ||
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy + 20 * px) && (Y <= oy + 20 * px);
	// Total 66 lines.

assign inWhite_eight = inHitBox_eight & ~inBlank_eight & ~inGrey_eight;

// End of Auto Generate: Number/eight

// Auto Generated: Number/five
localparam fiveWidth = 20 * px;
localparam fiveHeight = 21 * px;
wire inHitBox_five;
wire inGrey_five;
wire inBlank_five;
wire inWhite_five;

assign inHitBox_five = (X > ox) && (X <= fiveWidth) && (Y > oy) && (Y <= fiveHeight);

assign inGrey_five = 
     (X > ox) && (X <= ox + 14 * px) && (Y > oy) && (Y <= oy) ||
     (X > ox) && (X <= ox + 14 * px) && (Y > oy + 1 * px) && (Y <= oy + 1 * px) ||
     (X > ox) && (X <= ox + 14 * px) && (Y > oy + 2 * px) && (Y <= oy + 2 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 3 * px) && (Y <= oy + 3 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 4 * px) && (Y <= oy + 4 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 5 * px) && (Y <= oy + 5 * px) ||
     (X > ox) && (X <= ox + 14 * px) && (Y > oy + 6 * px) && (Y <= oy + 6 * px) ||
     (X > ox) && (X <= ox + 14 * px) && (Y > oy + 7 * px) && (Y <= oy + 7 * px) ||
     (X > ox) && (X <= ox + 14 * px) && (Y > oy + 8 * px) && (Y <= oy + 8 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 9 * px) && (Y <= oy + 9 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 10 * px) && (Y <= oy + 10 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 11 * px) && (Y <= oy + 11 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 12 * px) && (Y <= oy + 12 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 13 * px) && (Y <= oy + 13 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 14 * px) && (Y <= oy + 14 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 15 * px) && (Y <= oy + 15 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 15 * px) && (Y <= oy + 15 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 16 * px) && (Y <= oy + 16 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 16 * px) && (Y <= oy + 16 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 17 * px) && (Y <= oy + 17 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 17 * px) && (Y <= oy + 17 * px) ||
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy + 18 * px) && (Y <= oy + 18 * px) ||
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy + 19 * px) && (Y <= oy + 19 * px) ||
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy + 20 * px) && (Y <= oy + 20 * px);
	// Total 48 lines.

assign inWhite_five = inHitBox_five & ~inBlank_five & ~inGrey_five;

// End of Auto Generate: Number/five

// Auto Generated: Number/one
localparam oneWidth = 20 * px;
localparam oneHeight = 21 * px;
wire inHitBox_one;
wire inGrey_one;
wire inBlank_one;
wire inWhite_one;

assign inHitBox_one = (X > ox) && (X <= oneWidth) && (Y > oy) && (Y <= oneHeight);

assign inGrey_one = 
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy) && (Y <= oy) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 1 * px) && (Y <= oy + 1 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 2 * px) && (Y <= oy + 2 * px) ||
     (X > ox + 5 * px) && (X <= ox + 12 * px) && (Y > oy + 3 * px) && (Y <= oy + 3 * px) ||
     (X > ox + 5 * px) && (X <= ox + 12 * px) && (Y > oy + 4 * px) && (Y <= oy + 4 * px) ||
     (X > ox + 5 * px) && (X <= ox + 12 * px) && (Y > oy + 5 * px) && (Y <= oy + 5 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 6 * px) && (Y <= oy + 6 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 7 * px) && (Y <= oy + 7 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 8 * px) && (Y <= oy + 8 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 9 * px) && (Y <= oy + 9 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 10 * px) && (Y <= oy + 10 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 11 * px) && (Y <= oy + 11 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 12 * px) && (Y <= oy + 12 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 13 * px) && (Y <= oy + 13 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 14 * px) && (Y <= oy + 14 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 15 * px) && (Y <= oy + 15 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 16 * px) && (Y <= oy + 16 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 17 * px) && (Y <= oy + 17 * px) ||
     (X > ox + 2 * px) && (X <= ox + 17 * px) && (Y > oy + 18 * px) && (Y <= oy + 18 * px) ||
     (X > ox + 2 * px) && (X <= ox + 17 * px) && (Y > oy + 19 * px) && (Y <= oy + 19 * px) ||
     (X > ox + 2 * px) && (X <= ox + 17 * px) && (Y > oy + 20 * px) && (Y <= oy + 20 * px);
	// Total 42 lines.

assign inWhite_one = inHitBox_one & ~inBlank_one & ~inGrey_one;

// End of Auto Generate: Number/one

// Auto Generated: Number/seven
localparam sevenWidth = 20 * px;
localparam sevenHeight = 21 * px;
wire inHitBox_seven;
wire inGrey_seven;
wire inBlank_seven;
wire inWhite_seven;

assign inHitBox_seven = (X > ox) && (X <= sevenWidth) && (Y > oy) && (Y <= sevenHeight);

assign inGrey_seven = 
     (X > ox) && (X <= ox + 17 * px) && (Y > oy) && (Y <= oy) ||
     (X > ox) && (X <= ox + 17 * px) && (Y > oy + 1 * px) && (Y <= oy + 1 * px) ||
     (X > ox) && (X <= ox + 17 * px) && (Y > oy + 2 * px) && (Y <= oy + 2 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 3 * px) && (Y <= oy + 3 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 3 * px) && (Y <= oy + 3 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 4 * px) && (Y <= oy + 4 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 4 * px) && (Y <= oy + 4 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 5 * px) && (Y <= oy + 5 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 5 * px) && (Y <= oy + 5 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 6 * px) && (Y <= oy + 6 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 7 * px) && (Y <= oy + 7 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 8 * px) && (Y <= oy + 8 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 9 * px) && (Y <= oy + 9 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 10 * px) && (Y <= oy + 10 * px) ||
     (X > ox + 7 * px) && (X <= ox + 12 * px) && (Y > oy + 11 * px) && (Y <= oy + 11 * px) ||
     (X > ox + 5 * px) && (X <= ox + 9 * px) && (Y > oy + 12 * px) && (Y <= oy + 12 * px) ||
     (X > ox + 5 * px) && (X <= ox + 9 * px) && (Y > oy + 13 * px) && (Y <= oy + 13 * px) ||
     (X > ox + 5 * px) && (X <= ox + 9 * px) && (Y > oy + 14 * px) && (Y <= oy + 14 * px) ||
     (X > ox + 5 * px) && (X <= ox + 9 * px) && (Y > oy + 15 * px) && (Y <= oy + 15 * px) ||
     (X > ox + 5 * px) && (X <= ox + 9 * px) && (Y > oy + 16 * px) && (Y <= oy + 16 * px) ||
     (X > ox + 5 * px) && (X <= ox + 9 * px) && (Y > oy + 17 * px) && (Y <= oy + 17 * px) ||
     (X > ox + 5 * px) && (X <= ox + 9 * px) && (Y > oy + 18 * px) && (Y <= oy + 18 * px) ||
     (X > ox + 5 * px) && (X <= ox + 9 * px) && (Y > oy + 19 * px) && (Y <= oy + 19 * px) ||
     (X > ox + 5 * px) && (X <= ox + 9 * px) && (Y > oy + 20 * px) && (Y <= oy + 20 * px);
	// Total 48 lines.

assign inWhite_seven = inHitBox_seven & ~inBlank_seven & ~inGrey_seven;

// End of Auto Generate: Number/seven

// Auto Generated: Number/nine
localparam nineWidth = 18 * px;
localparam nineHeight = 21 * px;
wire inHitBox_nine;
wire inGrey_nine;
wire inBlank_nine;
wire inWhite_nine;

assign inHitBox_nine = (X > ox) && (X <= nineWidth) && (Y > oy) && (Y <= nineHeight);

assign inGrey_nine = 
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy) && (Y <= oy) ||
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy + 1 * px) && (Y <= oy + 1 * px) ||
     (X > ox + 2 * px) && (X <= ox + 14 * px) && (Y > oy + 2 * px) && (Y <= oy + 2 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 3 * px) && (Y <= oy + 3 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 3 * px) && (Y <= oy + 3 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 4 * px) && (Y <= oy + 4 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 4 * px) && (Y <= oy + 4 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 5 * px) && (Y <= oy + 5 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 5 * px) && (Y <= oy + 5 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 6 * px) && (Y <= oy + 6 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 6 * px) && (Y <= oy + 6 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 7 * px) && (Y <= oy + 7 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 7 * px) && (Y <= oy + 7 * px) ||
     (X > ox) && (X <= ox + 4 * px) && (Y > oy + 8 * px) && (Y <= oy + 8 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 8 * px) && (Y <= oy + 8 * px) ||
     (X > ox + 2 * px) && (X <= ox + 17 * px) && (Y > oy + 9 * px) && (Y <= oy + 9 * px) ||
     (X > ox + 2 * px) && (X <= ox + 17 * px) && (Y > oy + 10 * px) && (Y <= oy + 10 * px) ||
     (X > ox + 2 * px) && (X <= ox + 17 * px) && (Y > oy + 11 * px) && (Y <= oy + 11 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 12 * px) && (Y <= oy + 12 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 13 * px) && (Y <= oy + 13 * px) ||
     (X > ox + 12 * px) && (X <= ox + 17 * px) && (Y > oy + 14 * px) && (Y <= oy + 14 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 15 * px) && (Y <= oy + 15 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 16 * px) && (Y <= oy + 16 * px) ||
     (X > ox + 10 * px) && (X <= ox + 14 * px) && (Y > oy + 17 * px) && (Y <= oy + 17 * px) ||
     (X > ox + 2 * px) && (X <= ox + 12 * px) && (Y > oy + 18 * px) && (Y <= oy + 18 * px) ||
     (X > ox + 2 * px) && (X <= ox + 12 * px) && (Y > oy + 19 * px) && (Y <= oy + 19 * px) ||
     (X > ox + 2 * px) && (X <= ox + 12 * px) && (Y > oy + 20 * px) && (Y <= oy + 20 * px);
	// Total 54 lines.

assign inWhite_nine = inHitBox_nine & ~inBlank_nine & ~inGrey_nine;

// End of Auto Generate: Number/nine


case(select) begin
3'b/*SEL*/ : begin
	assign inHitBox = inHitBox_three;
	assign inWhite = inWhite_three;
	assign inGrey = inGrey_three;
end

3'b/*SEL*/ : begin
	assign inHitBox = inHitBox_six;
	assign inWhite = inWhite_six;
	assign inGrey = inGrey_six;
end

3'b/*SEL*/ : begin
	assign inHitBox = inHitBox_two;
	assign inWhite = inWhite_two;
	assign inGrey = inGrey_two;
end

3'b/*SEL*/ : begin
	assign inHitBox = inHitBox_four;
	assign inWhite = inWhite_four;
	assign inGrey = inGrey_four;
end

3'b/*SEL*/ : begin
	assign inHitBox = inHitBox_zero;
	assign inWhite = inWhite_zero;
	assign inGrey = inGrey_zero;
end

3'b/*SEL*/ : begin
	assign inHitBox = inHitBox_eight;
	assign inWhite = inWhite_eight;
	assign inGrey = inGrey_eight;
end

3'b/*SEL*/ : begin
	assign inHitBox = inHitBox_five;
	assign inWhite = inWhite_five;
	assign inGrey = inGrey_five;
end

3'b/*SEL*/ : begin
	assign inHitBox = inHitBox_one;
	assign inWhite = inWhite_one;
	assign inGrey = inGrey_one;
end

3'b/*SEL*/ : begin
	assign inHitBox = inHitBox_seven;
	assign inWhite = inWhite_seven;
	assign inGrey = inGrey_seven;
end

3'b/*SEL*/ : begin
	assign inHitBox = inHitBox_nine;
	assign inWhite = inWhite_nine;
	assign inGrey = inGrey_nine;
end


endcase

/* Enter Selector Code here */



endmodule // end of Number
