// AutoGenerate.py Version 1.1
// The following content is auto generated by AutoGenerate.py
// Written by Zijian Zhao
// github.com/JackZhao98
// Date created: 2020/03/01  21:13:29


//	Selector Summary
//	4'b0001	: Cloud


module drawDecor#(parameter ratio = 1)
	(
	    input  wire        rst,
	    input  wire [31:0] ox,
	    input  wire [31:0] oy,
	    input  wire [31:0] X,
	    input  wire [31:0] Y,
	    input  wire [3:0]  select,	// Select Pattern
	    output reg  [10:0] objectWidth,
	    output reg  [10:0] objectHeight,
	    output reg 	       inHitBox,
	    output reg 	       inWhite,
	    output reg 	       inGrey);
		
localparam px = ratio;


// Auto Generated: Decor/Cloud
localparam CloudWidth = 92 * px;
localparam CloudHeight = 27 * px;
wire inHitBox_Cloud;
wire inGrey_Cloud;
wire inBlank_Cloud;
wire inWhite_Cloud;

assign inHitBox_Cloud = (X > ox) && (X <= CloudWidth) && (Y > oy) && (Y <= CloudHeight);

assign inBlank_Cloud = 
	   ((X > ox) && (X <= ox + 49 * px) && (Y == oy))
	|| ((X > ox + 58 * px) && (X <= ox + 91 * px) && (Y == oy))
	|| ((X > ox) && (X <= ox + 49 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 58 * px) && (X <= ox + 91 * px) && (Y == oy + 1 * px))
	|| ((X > ox) && (X <= ox + 39 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 52 * px) && (X <= ox + 55 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 62 * px) && (X <= ox + 91 * px) && (Y == oy + 2 * px))
	|| ((X > ox) && (X <= ox + 39 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 52 * px) && (X <= ox + 55 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 62 * px) && (X <= ox + 91 * px) && (Y == oy + 3 * px))
	|| ((X > ox) && (X <= ox + 37 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 42 * px) && (X <= ox + 59 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 62 * px) && (X <= ox + 91 * px) && (Y == oy + 4 * px))
	|| ((X > ox) && (X <= ox + 37 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 42 * px) && (X <= ox + 59 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 64 * px) && (X <= ox + 91 * px) && (Y == oy + 5 * px))
	|| ((X > ox) && (X <= ox + 33 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 40 * px) && (X <= ox + 59 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 64 * px) && (X <= ox + 91 * px) && (Y == oy + 6 * px))
	|| ((X > ox) && (X <= ox + 33 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 40 * px) && (X <= ox + 61 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 64 * px) && (X <= ox + 91 * px) && (Y == oy + 7 * px))
	|| ((X > ox) && (X <= ox + 33 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 36 * px) && (X <= ox + 61 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 64 * px) && (X <= ox + 91 * px) && (Y == oy + 8 * px))
	|| ((X > ox) && (X <= ox + 33 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 36 * px) && (X <= ox + 61 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 70 * px) && (X <= ox + 91 * px) && (Y == oy + 9 * px))
	|| ((X > ox) && (X <= ox + 33 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 36 * px) && (X <= ox + 61 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 70 * px) && (X <= ox + 91 * px) && (Y == oy + 10 * px))
	|| ((X > ox) && (X <= ox + 33 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 36 * px) && (X <= ox + 61 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 64 * px) && (X <= ox + 67 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 80 * px) && (X <= ox + 91 * px) && (Y == oy + 11 * px))
	|| ((X > ox) && (X <= ox + 27 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 36 * px) && (X <= ox + 61 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 64 * px) && (X <= ox + 67 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 80 * px) && (X <= ox + 91 * px) && (Y == oy + 12 * px))
	|| ((X > ox) && (X <= ox + 27 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 36 * px) && (X <= ox + 59 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 62 * px) && (X <= ox + 77 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 80 * px) && (X <= ox + 91 * px) && (Y == oy + 13 * px))
	|| ((X > ox) && (X <= ox + 25 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 30 * px) && (X <= ox + 59 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 62 * px) && (X <= ox + 77 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 80 * px) && (X <= ox + 91 * px) && (Y == oy + 14 * px))
	|| ((X > ox) && (X <= ox + 25 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 30 * px) && (X <= ox + 77 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 86 * px) && (X <= ox + 91 * px) && (Y == oy + 15 * px))
	|| ((X > ox) && (X <= ox + 11 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 28 * px) && (X <= ox + 77 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 86 * px) && (X <= ox + 91 * px) && (Y == oy + 16 * px))
	|| ((X > ox) && (X <= ox + 11 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 28 * px) && (X <= ox + 83 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 86 * px) && (X <= ox + 91 * px) && (Y == oy + 17 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 14 * px) && (X <= ox + 83 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 86 * px) && (X <= ox + 91 * px) && (Y == oy + 18 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 14 * px) && (X <= ox + 83 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 90 * px) && (X <= ox + 91 * px) && (Y == oy + 19 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 20 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 83 * px) && (Y == oy + 20 * px))
	|| ((X > ox + 90 * px) && (X <= ox + 91 * px) && (Y == oy + 20 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 21 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 87 * px) && (Y == oy + 21 * px))
	|| ((X > ox + 90 * px) && (X <= ox + 91 * px) && (Y == oy + 21 * px))
	|| ((X > ox) && (X <= ox + 9 * px) && (Y == oy + 22 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 87 * px) && (Y == oy + 22 * px))
	|| ((X > ox + 90 * px) && (X <= ox + 91 * px) && (Y == oy + 22 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 23 * px))
	|| ((X > ox + 6 * px) && (X <= ox + 7 * px) && (Y == oy + 23 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 23 * px))
	|| ((X > ox + 20 * px) && (X <= ox + 89 * px) && (Y == oy + 23 * px))
	|| ((X > ox) && (X <= ox + 1 * px) && (Y == oy + 24 * px))
	|| ((X > ox + 6 * px) && (X <= ox + 7 * px) && (Y == oy + 24 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 17 * px) && (Y == oy + 24 * px))
	|| ((X > ox + 20 * px) && (X <= ox + 89 * px) && (Y == oy + 24 * px))
	|| ((X > ox + 4 * px) && (X <= ox + 19 * px) && (Y == oy + 25 * px))
	|| ((X > ox + 4 * px) && (X <= ox + 19 * px) && (Y == oy + 26 * px));
	// Total 162 lines.

assign inGrey_Cloud = 
	   ((X > ox + 50 * px) && (X <= ox + 57 * px) && (Y == oy))
	|| ((X > ox + 50 * px) && (X <= ox + 57 * px) && (Y == oy + 1 * px))
	|| ((X > ox + 40 * px) && (X <= ox + 51 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 56 * px) && (X <= ox + 61 * px) && (Y == oy + 2 * px))
	|| ((X > ox + 40 * px) && (X <= ox + 51 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 56 * px) && (X <= ox + 61 * px) && (Y == oy + 3 * px))
	|| ((X > ox + 38 * px) && (X <= ox + 41 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 60 * px) && (X <= ox + 61 * px) && (Y == oy + 4 * px))
	|| ((X > ox + 38 * px) && (X <= ox + 41 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 60 * px) && (X <= ox + 63 * px) && (Y == oy + 5 * px))
	|| ((X > ox + 34 * px) && (X <= ox + 39 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 60 * px) && (X <= ox + 63 * px) && (Y == oy + 6 * px))
	|| ((X > ox + 34 * px) && (X <= ox + 39 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 62 * px) && (X <= ox + 63 * px) && (Y == oy + 7 * px))
	|| ((X > ox + 34 * px) && (X <= ox + 35 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 62 * px) && (X <= ox + 63 * px) && (Y == oy + 8 * px))
	|| ((X > ox + 34 * px) && (X <= ox + 35 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 62 * px) && (X <= ox + 69 * px) && (Y == oy + 9 * px))
	|| ((X > ox + 34 * px) && (X <= ox + 35 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 62 * px) && (X <= ox + 69 * px) && (Y == oy + 10 * px))
	|| ((X > ox + 34 * px) && (X <= ox + 35 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 62 * px) && (X <= ox + 63 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 68 * px) && (X <= ox + 79 * px) && (Y == oy + 11 * px))
	|| ((X > ox + 28 * px) && (X <= ox + 35 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 62 * px) && (X <= ox + 63 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 68 * px) && (X <= ox + 79 * px) && (Y == oy + 12 * px))
	|| ((X > ox + 28 * px) && (X <= ox + 35 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 60 * px) && (X <= ox + 61 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 78 * px) && (X <= ox + 79 * px) && (Y == oy + 13 * px))
	|| ((X > ox + 26 * px) && (X <= ox + 29 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 60 * px) && (X <= ox + 61 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 78 * px) && (X <= ox + 79 * px) && (Y == oy + 14 * px))
	|| ((X > ox + 26 * px) && (X <= ox + 29 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 78 * px) && (X <= ox + 85 * px) && (Y == oy + 15 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 27 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 78 * px) && (X <= ox + 85 * px) && (Y == oy + 16 * px))
	|| ((X > ox + 12 * px) && (X <= ox + 27 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 84 * px) && (X <= ox + 85 * px) && (Y == oy + 17 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 13 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 84 * px) && (X <= ox + 85 * px) && (Y == oy + 18 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 13 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 84 * px) && (X <= ox + 89 * px) && (Y == oy + 19 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 11 * px) && (Y == oy + 20 * px))
	|| ((X > ox + 84 * px) && (X <= ox + 89 * px) && (Y == oy + 20 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 11 * px) && (Y == oy + 21 * px))
	|| ((X > ox + 88 * px) && (X <= ox + 89 * px) && (Y == oy + 21 * px))
	|| ((X > ox + 10 * px) && (X <= ox + 11 * px) && (Y == oy + 22 * px))
	|| ((X > ox + 88 * px) && (X <= ox + 89 * px) && (Y == oy + 22 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 5 * px) && (Y == oy + 23 * px))
	|| ((X > ox + 8 * px) && (X <= ox + 11 * px) && (Y == oy + 23 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 23 * px))
	|| ((X > ox + 90 * px) && (X <= ox + 91 * px) && (Y == oy + 23 * px))
	|| ((X > ox + 2 * px) && (X <= ox + 5 * px) && (Y == oy + 24 * px))
	|| ((X > ox + 8 * px) && (X <= ox + 11 * px) && (Y == oy + 24 * px))
	|| ((X > ox + 18 * px) && (X <= ox + 19 * px) && (Y == oy + 24 * px))
	|| ((X > ox + 90 * px) && (X <= ox + 91 * px) && (Y == oy + 24 * px))
	|| ((X > ox) && (X <= ox + 3 * px) && (Y == oy + 25 * px))
	|| ((X > ox + 20 * px) && (X <= ox + 91 * px) && (Y == oy + 25 * px))
	|| ((X > ox) && (X <= ox + 3 * px) && (Y == oy + 26 * px))
	|| ((X > ox + 20 * px) && (X <= ox + 91 * px) && (Y == oy + 26 * px));
	// Total 120 lines.

assign inWhite_Cloud = inHitBox_Cloud & ~inBlank_Cloud & ~inGrey_Cloud;

// End of Auto Generate: Decor/Cloud


always @(*) begin

case(select)

4'b0001: begin	// Case: Cloud
	inHitBox <= inHitBox_Cloud;
	inWhite <= inWhite_Cloud;
	inGrey <= inGrey_Cloud;
	objectWidth <= CloudWidth;
	objectHeight <= CloudHeight;
end // end of case


endcase

end	// end of always @(*)

endmodule // end of Decor

// Auto generate complete.
// Direct modification of this file may cause unexpected issues.
// Copyright © 2020 Zijian Zhao. All rights reserved.
		
